
name: "testing testing"
inputs:
  who-to-greet:
    description: "Who should I hello"
    required: true
    default: "World"

outputs:
  time:
    description: "Time when executed"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-greet}}
