name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "45 6 * * 0"
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: ${{ github.event.name }}"
          echo "branch: ${{ github.ref }}

      - uses: actions/checkout@v3.3.0
      
      - name: List
        run: tree
    
    
