name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "45 6 * * 0"
  workflow_dispatch:
    inputs: 
      environment:
        description: "Environment"
        type: environment
        required: true
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: ${{ github.event_name }}"
          echo "branch: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0
      
      - name: List
        run: tree
  Test:
    runs-on: ubuntu-latest
    if: gitbug.event_name == 'workflow_dispatch'
    needs: Build
    steps: |
      - run: echo "testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: gitbug.event_name == 'workflow_dispatch'
    steps: |
      - run: echo "Testing..."
  Production:
    needs: [Test, Load-Test]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://writeabout.net'
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
      - run: |
          echo "step 2 deploying..."
          sleep 10
      - run: |
          echo "step 3 deploying..."
          sleep 10
      - run: |
          echo "step 4 deploying..."
          sleep 10
      - run: |
          echo "step 5 deploying..."
          sleep 10
      
      
    
